apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-04-01T17:56:15Z
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "6971"
  selfLink: /api/v1/namespaces/default/services/nginx
  uid: 568f681f-3745-11e8-b911-42010a8000ad
spec:
  clusterIP: 10.11.248.218
  ports:
  - nodePort: 31212
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
